version: '3.7'

services:
  db:
    image: postgres:11.6
    init: true
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  backend:
    build:
      context: ./test_task_backend
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./test_task_backend:/usr/src/app
      - venv:/usr/src/app/venv
    env_file:
      - ./test_task_backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py load_data && python manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: ./test_task_frontend
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./test_task_frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    ports:
      - 3000:3000
volumes:
  db-data:
  venv:
  node_modules:
